import { defineField, defineType } from "sanity";
import { imageAltField, siteImageHotspot } from "../imageHotspot";
import {
  ProductHeightInput,
  ProductLengthInput,
  ProductLoadCapacityInput,
  ProductOverallHeightInput,
  ProductOverallLengthInput,
  ProductOverallWidthInput,
  ProductShapeInput,
  ProductShapesInput,
  ProductMaterialsInput,
  ProductSizeInput,
  ProductWidthInput,
} from "../components/ProductDimensionInputs";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "basic", title: "Basic", default: true },
    { name: "specs", title: "Specs" },
    { name: "media", title: "Media" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "basic",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "basic",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "series",
      title: "Series",
      type: "string",
      group: "basic",
      options: {
        list: [
          { title: "Pod", value: "pod" },
          { title: "Airstream", value: "airstream" },
          { title: "Square", value: "square" },
          { title: "Container", value: "container" },
          { title: "Capsule", value: "capsule" },
          { title: "Others", value: "others" },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      group: "basic",
    }),
    defineField({
      name: "sku",
      title: "SKU",
      type: "string",
      group: "basic",
    }),
    defineField({
      name: "length",
      title: "Body length (mm)",
      type: "number",
      group: "specs",
      description: "箱体长度，不含拖杠。筛选和自定义器用这个。选完后 Body size 会自动生成。",
      components: { input: ProductLengthInput },
    }),
    defineField({
      name: "width",
      title: "Body width (mm)",
      type: "number",
      group: "specs",
      description: "箱体宽度。下拉选项来自该系列产品页筛选。",
      components: { input: ProductWidthInput },
    }),
    defineField({
      name: "height",
      title: "Body height (mm)",
      type: "number",
      group: "specs",
      description: "箱体高度。有值时 Body size 为 长×宽×高 mm。",
      components: { input: ProductHeightInput },
    }),
    defineField({
      name: "size",
      title: "Body size",
      type: "string",
      group: "specs",
      description: "随箱体长、宽、高即时显示（长×宽 mm，有高度则为 长×宽×高 mm）。只读，不写入文档。改上面三个下拉即可看到结果。",
      readOnly: true,
      components: { input: ProductSizeInput },
    }),
    defineField({
      name: "overallLength",
      title: "Overall length (mm)",
      type: "number",
      group: "specs",
      description: "整车长度 = 箱体长度 + 1440（拖杠）。只读展示，按箱体长度计算。",
      readOnly: true,
      components: { input: ProductOverallLengthInput },
    }),
    defineField({
      name: "overallWidth",
      title: "Overall width (mm)",
      type: "number",
      group: "specs",
      description: "整车宽度 = 箱体宽度。只读展示，按箱体宽度计算。",
      readOnly: true,
      components: { input: ProductOverallWidthInput },
    }),
    defineField({
      name: "overallHeight",
      title: "Overall height (mm)",
      type: "number",
      group: "specs",
      description: "整车高度。2400 / 2500 / 2600。只显示在产品详情页规格表。",
      components: { input: ProductOverallHeightInput },
    }),
    defineField({
      name: "weight",
      title: "Weight (KG)",
      type: "number",
      group: "specs",
      description: "整车重量，单位 KG。详情页显示为 850KG。卡片不显示。",
    }),
    defineField({
      name: "loadCapacity",
      title: "Load capacity (KG)",
      type: "number",
      group: "specs",
      description: "载重，单位 KG。详情页显示为 1250KG。卡片不显示。",
      components: { input: ProductLoadCapacityInput },
    }),
    defineField({
      name: "axle",
      title: "Axle",
      type: "string",
      group: "specs",
      options: {
        list: [
          { title: "Single Axle", value: "Single Axle" },
          { title: "Tandem Axle", value: "Tandem Axle" },
        ],
      },
    }),
    defineField({
      name: "stockStatus",
      title: "Stock status",
      type: "string",
      group: "specs",
      options: {
        list: [
          { title: "In Stock", value: "In Stock" },
          { title: "Made to Order", value: "Made to Order" },
          { title: "Out of Stock", value: "Out of Stock" },
        ],
      },
    }),
    defineField({
      name: "materials",
      title: "Materials (options on this model)",
      type: "array",
      group: "specs",
      description:
        "同一车型的可选材质，不要为喷漆 / 不锈钢各建一条产品。Capsule、Airstream 通常勾 Paint + Stainless steel；Square / Container / Pod 只勾 Paint。",
      of: [{ type: "string" }],
      components: { input: ProductMaterialsInput },
    }),
    defineField({
      name: "material",
      title: "Material (legacy)",
      type: "string",
      group: "specs",
      hidden: true,
      options: {
        list: [
          { title: "Paint", value: "Paint" },
          { title: "Stainless steel", value: "Stainless steel" },
          { title: "Titanium", value: "Titanium" },
        ],
      },
    }),
    defineField({
      name: "shapes",
      title: "Shapes (options on this model)",
      type: "array",
      group: "specs",
      description:
        "同一车型的可选造型，不要为每种造型各建一条产品。Pod：Dome + Square；Airstream：375 / 500 / 700 Arc。Square / Container 只勾 Square；Capsule 只勾 375 Arc。",
      of: [{ type: "string" }],
      components: { input: ProductShapesInput },
    }),
    defineField({
      name: "shape",
      title: "Shape (legacy)",
      type: "string",
      group: "specs",
      hidden: true,
      components: { input: ProductShapeInput },
    }),
    defineField({
      name: "mainImage",
      title: "Main image",
      type: "image",
      group: "media",
      description: "拖圆点到车身中心后点 Done，再 Publish。",
      options: { hotspot: siteImageHotspot },
      fields: [imageAltField],
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "media",
      description: "详情页缩略图。可不含主图；空则只显示主图。",
      of: [{ type: "image", options: { hotspot: siteImageHotspot }, fields: [imageAltField] }],
    }),
    defineField({
      name: "features",
      title: "Included (this SKU only)",
      type: "array",
      group: "specs",
      hidden: true,
      description: "仅当这一台和系列默认不同时填写。平时请改系列页 Included。",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "customOptions",
      title: "Can be customized (this SKU only)",
      type: "array",
      group: "specs",
      hidden: true,
      description: "仅当这一台和全站默认不同时填写。平时请改首页 Page Content 的 Can be customized。",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "viewProductText",
      title: "View product 按钮文字",
      type: "string",
      group: "basic",
      description: "留空显示 View product。预览里点蓝标可改文字。",
    }),
    defineField({
      name: "viewProductLink",
      title: "View product 按钮链接",
      type: "string",
      group: "basic",
      description: "留空则打开本产品详情页。可填 /contact 或 https://...。预览里点击按钮会跳转；改链接请用右侧这个字段。",
    }),
    defineField({
      name: "quoteText",
      title: "Get Quote 按钮文字",
      type: "string",
      group: "basic",
      description: "留空显示 Get Quote。预览里点蓝标可改文字。",
    }),
    defineField({
      name: "quoteLink",
      title: "Get Quote 按钮链接",
      type: "string",
      group: "basic",
      description: "留空则打开询盘页并带上本产品。可填 /contact 或 https://...。预览里点按钮蓝标改链接。",
    }),
    defineField({
      name: "customizeText",
      title: "Customize 按钮文字",
      type: "string",
      group: "basic",
      description: "留空显示 Customize your own。",
    }),
    defineField({
      name: "customizeLink",
      title: "Customize 按钮链接",
      type: "string",
      group: "basic",
      description: "留空则打开 /customize 并带上本产品。",
    }),
    defineField({ name: "price", title: "Price", type: "number", hidden: true }),
    defineField({ name: "priceHigh", title: "Price high (USD)", type: "number", hidden: true }),
    defineField({ name: "axles", title: "Axles (count)", type: "number", hidden: true }),
    defineField({ name: "stock", title: "Stock (legacy)", type: "string", hidden: true }),
    defineField({ name: "year", title: "Year", type: "number", hidden: true }),
    defineField({ name: "scene", title: "Scene", type: "string", hidden: true }),
    defineField({ name: "glassCount", title: "Glass count", type: "string", hidden: true }),
    defineField({ name: "glassHeight", title: "Glass height", type: "string", hidden: true }),
    defineField({
      name: "images",
      title: "Legacy images",
      type: "array",
      group: "media",
      description:
        "旧图库。以前会混进详情页缩略图。请把要保留的图移到上面 Gallery，不要的点条目左侧菜单 Remove item。",
      of: [{ type: "image", options: { hotspot: siteImageHotspot }, fields: [imageAltField] }],
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "sku", media: "mainImage" },
  },
});
